# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resizeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ResizeDialog(object):
    def setupUi(self, ResizeDialog):
        ResizeDialog.setObjectName("ResizeDialog")
        ResizeDialog.resize(377, 348)
        self.gridLayout_2 = QtWidgets.QGridLayout(ResizeDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(ResizeDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.widthEdit = QtWidgets.QLineEdit(ResizeDialog)
        self.widthEdit.setObjectName("widthEdit")
        self.horizontalLayout.addWidget(self.widthEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.buttonTopLeft = QtWidgets.QPushButton(ResizeDialog)
        self.buttonTopLeft.setText("")
        self.buttonTopLeft.setCheckable(True)
        self.buttonTopLeft.setObjectName("buttonTopLeft")
        self.gridLayout.addWidget(self.buttonTopLeft, 0, 0, 1, 1)
        self.buttonTop = QtWidgets.QPushButton(ResizeDialog)
        self.buttonTop.setText("")
        self.buttonTop.setCheckable(True)
        self.buttonTop.setObjectName("buttonTop")
        self.gridLayout.addWidget(self.buttonTop, 0, 1, 1, 1)
        self.buttonTopRight = QtWidgets.QPushButton(ResizeDialog)
        self.buttonTopRight.setText("")
        self.buttonTopRight.setCheckable(True)
        self.buttonTopRight.setObjectName("buttonTopRight")
        self.gridLayout.addWidget(self.buttonTopRight, 0, 2, 1, 1)
        self.buttonLeft = QtWidgets.QPushButton(ResizeDialog)
        self.buttonLeft.setText("")
        self.buttonLeft.setCheckable(True)
        self.buttonLeft.setObjectName("buttonLeft")
        self.gridLayout.addWidget(self.buttonLeft, 1, 0, 1, 1)
        self.buttonCenter = QtWidgets.QPushButton(ResizeDialog)
        self.buttonCenter.setText("")
        self.buttonCenter.setCheckable(True)
        self.buttonCenter.setObjectName("buttonCenter")
        self.gridLayout.addWidget(self.buttonCenter, 1, 1, 1, 1)
        self.buttonRight = QtWidgets.QPushButton(ResizeDialog)
        self.buttonRight.setText("")
        self.buttonRight.setCheckable(True)
        self.buttonRight.setObjectName("buttonRight")
        self.gridLayout.addWidget(self.buttonRight, 1, 2, 1, 1)
        self.buttonBottomLeft = QtWidgets.QPushButton(ResizeDialog)
        self.buttonBottomLeft.setText("")
        self.buttonBottomLeft.setCheckable(True)
        self.buttonBottomLeft.setObjectName("buttonBottomLeft")
        self.gridLayout.addWidget(self.buttonBottomLeft, 2, 0, 1, 1)
        self.buttonBottom = QtWidgets.QPushButton(ResizeDialog)
        self.buttonBottom.setText("")
        self.buttonBottom.setCheckable(True)
        self.buttonBottom.setObjectName("buttonBottom")
        self.gridLayout.addWidget(self.buttonBottom, 2, 1, 1, 1)
        self.buttonBottomRight = QtWidgets.QPushButton(ResizeDialog)
        self.buttonBottomRight.setText("")
        self.buttonBottomRight.setCheckable(True)
        self.buttonBottomRight.setObjectName("buttonBottomRight")
        self.gridLayout.addWidget(self.buttonBottomRight, 2, 2, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(ResizeDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.heightEdit = QtWidgets.QLineEdit(ResizeDialog)
        self.heightEdit.setObjectName("heightEdit")
        self.horizontalLayout_2.addWidget(self.heightEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(ResizeDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 3, 0, 1, 1)

        self.retranslateUi(ResizeDialog)
        self.buttonBox.accepted.connect(ResizeDialog.accept)
        self.buttonBox.rejected.connect(ResizeDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ResizeDialog)
        ResizeDialog.setTabOrder(self.widthEdit, self.heightEdit)
        ResizeDialog.setTabOrder(self.heightEdit, self.buttonTopLeft)
        ResizeDialog.setTabOrder(self.buttonTopLeft, self.buttonTop)
        ResizeDialog.setTabOrder(self.buttonTop, self.buttonTopRight)
        ResizeDialog.setTabOrder(self.buttonTopRight, self.buttonLeft)
        ResizeDialog.setTabOrder(self.buttonLeft, self.buttonCenter)
        ResizeDialog.setTabOrder(self.buttonCenter, self.buttonRight)
        ResizeDialog.setTabOrder(self.buttonRight, self.buttonBottomLeft)
        ResizeDialog.setTabOrder(self.buttonBottomLeft, self.buttonBottom)
        ResizeDialog.setTabOrder(self.buttonBottom, self.buttonBottomRight)

    def retranslateUi(self, ResizeDialog):
        _translate = QtCore.QCoreApplication.translate
        ResizeDialog.setWindowTitle(_translate("ResizeDialog", "Set size"))
        self.label.setText(_translate("ResizeDialog", "Width:"))
        self.label_2.setText(_translate("ResizeDialog", "Height:"))

